---
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.90.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
    -   id: shellcheck
